### ISSUE TITLE
[FEATURE] Gpt로 홍보글 작성 API 구현

### ISSUE THREAD

**Issue by ItsZetty** [LuckyYoungNam/Server#18]
## ⚒️ Issue
Gpt로 홍보글 작성 API 구현해야 함.

## 📝 To-do
- [x] Gpt 연결
- [ ] 홍보글 프롬프트 조정
- [x] 변환된 홍보글 저장 API 구현
- [x] 클라이언트에 변환된 홍보글 반환하는 API 구현
