### ISSUE TITLE
[FEATURE] 홍보 사진 관련 API 구현

### ISSUE THREAD

**Issue by ItsZetty** [LuckyYoungNam/Server#32]
## ⚒️ Issue
홍보 사진 관련 API 구현해야 함.

## 📝 To-do
- [x] 홍보 사진 받아오기
- [x] 홍보 사진 리사이징
- [x] 홍보 사진 저장
- [x] 홍보 사진 반환
- [x] 변환된 홍보 사진 받아오기
- [x] 변환된 홍보 사진 리사이징
- [x] 변환된 홍보 사진 저장
