### ISSUE TITLE
[FEATURE] 홍보글 관련 API 구현

### ISSUE THREAD

**Issue by ItsZetty** [LuckyYoungNam/Server#4]
## ⚒️ Issue
홍보글 관련 API 구현해야 함.

## 📝 To-do
- [x] 초기 홍보글 저장 
- [x] 홍보글 변환 후 반환
- [x] 최종 홍보글 저장

## 📂 ETC
- Open AI 연결해야 함
